### ISSUE TITLE
Create namespace "\Mongofill" for all classes

### ISSUE THREAD

**Issue by benms** [mongofill/mongofill#107]
Create namespace "\Mongofill" for all classes

**Comment by pmaselkowski** [comment]
This project is supposed to be replacement for PHP's extension, so class names are in global namespace and have very specific signatures - to use directly instead of extension.

**Comment by benms** [comment]
MongoFill is also conflict with standard PHPStorm MongoDB methods


<a href="https://www.mongodb.com" rel="some text">![Foo](http://screen.mindklab.com/incoming/84598f239b68c397f56088c9f79e.png)</a>

**Comment by benms** [comment]
Also problems in PHPStorm IDE when resolving standard MongoDB methods

<a href="http://mongodb.com/" rel="some text">![Foo](http://screen.mindklab.com/incoming/84598f239b68c397f56088c9f79e.png)</a>

How to solve it?

**Comment by pmaselkowski** [comment]
I'm not familiar with PHP storm, but the issue here is that it have (intentionally) same class names as said extension. 

You could add to ignored list `/vendor/mongofill/` so IDE will use completion from PHPStorm stub (this approach works in NetBeans).
