### ISSUE TITLE
HHVM server crashing

### ISSUE THREAD

**Issue by partypete** [mongofill/mongofill#64]
hello, I'm trying to run mongofill with hhvm, and whenever my php script calls for mongo, server crashes without any error, can anyone help?

my hhvm version is: 3.5.0-dev
any suggestions?

**Comment by digitalkaoz** [comment]
hhvm 3.5 changed to extension api...try it with 3.4

**Comment by partypete** [comment]
Just few minutes ago I've managed to get it working, only had to install hhvm-seg for segfaults and now it's ok
