### ISSUE TITLE
MongoId::generateId is slow

### ISSUE THREAD

**Issue by ElectroLutz** [mongofill/mongofill#72]
Hey,

some testing with HHVM and PHP5-FPM showed that the MongoId::generateId implementation is kinda slow.

I used the following snippet to test the performance:

```php
$n = 50000;
$start = microtime(true);
for ($i = 0; $i < $n; $i++) {
    new \MongoId();
}
echo $n . ' instantiations took: ' . (microtime(true) - $start) . ' seconds';
```

My test system uses PHP5-FPM 5.5.9 (OpCache enabled) and HHVM 3.6.1 on Ubuntu 14.04.

WITHOUT mongofill on PHP5-FPM using the current version of the mongo-php-driver (installed today):
```
50000 instantiations took: 0.064556837081909 seconds
```

WITH mongofill:

PHP5-FPM:
```
50000 instantiation took: 0.70950603485107 seconds
```

HHVM:
```
50000 instantiations took: 0.58470797538757 seconds
```

As you can see the generateId of mongo-php-driver is 10x faster than mongofills. 

I'm looking forward to see a patch for this and thank you in advance!

Cheers
Marko

**Comment by mcuadros** [comment]
The mongo-php-driver is written C in the other hand mongofill is written on PHP, we cannot beat the performance of C. [Some parts](https://github.com/mongofill/mongofill-hhvm) of mongofill are written on C++ increasing the performance, but other parts like this is on PHP.

Any PRs will be more than welcome.
