### ISSUE TITLE
fatal error: hphp/runtime/base/base-includes.h

### ISSUE THREAD

**Issue by nesX** [mongofill/mongofill#74]
./build.sh 

git submodule update --init
hhvm tools/merge.php
hphpize
** hphpize complete, now run `cmake . && make` to build, `make test` to test
cmake .
-- Configuring for HHVM API version 20150212
-- bson Include dir: /usr/include/libbson-1.0
-- libbson library: /usr/local/lib/libbson-1.0.so
-- Configuring done
-- Generating done
-- Build files have been written to: /nesx/library/mongofill-hhvm
make
[ 33%] Building CXX object CMakeFiles/mongo.dir/src/bson.cpp.o
/nesx/library/mongofill-hhvm/src/bson.cpp:1:45: fatal error: hphp/runtime/base/base-includes.h: No such file or directory
 #include "hphp/runtime/base/base-includes.h"
                                             ^
compilation terminated.
make[2]: *** [CMakeFiles/mongo.dir/src/bson.cpp.o] Error 1
make[1]: *** [CMakeFiles/mongo.dir/all] Error 2
make: *** [all] Error 2

**Comment by aftabnaveed** [comment]
getting the same error any idea what's is going wrong, if I won't link any library it just generates the build fine, but then no use of it :sa:

**Comment by mcuadros** [comment]
can you try with the latest versions?
