### ISSUE TITLE
SOL_TCP constant is not defined on BSD systems.

### ISSUE THREAD

**Issue by mkeen** [mongofill/mongofill#76]
Mongofill is unable to connect to MongoDB at all on BSD distros because the SOL_TCP constant will not be defined. The workaround is simple, and works on BSD, *nix, Windows, etc. Let me know if you need any more details or if I should submit the pull request in a different format.

**Comment by mcuadros** [comment]
Thanks!

**Comment by mkeen** [comment]
You're welcome!
