### ISSUE TITLE
Authentication is not working with Mongo 3.0.3

### ISSUE THREAD

**Issue by blasterz** [mongofill/mongofill#77]
$m = new MongoClient('mongodb://user:pass@localhost/db');
$db = $m->db;
$res = $db->test->findOne();
var_dump($res);

The output is: 
array(2) {
  ["$err"]=>
  string(40) "not authorized for query on db.test"
  ["code"]=>
  int(13)
}

**Comment by ppetermann** [comment]
are you sure that your settings are right?

**Comment by blasterz** [comment]
Yes, I also tried the same thing with PyMongo in Python and it works.

**Comment by blasterz** [comment]
It seems like the MONGODB-CR authentication is used, which is not the default and is deprecated in Mongo 3

**Comment by mcuadros** [comment]
can you test with this pr -> https://github.com/mongofill/mongofill/pull/65 can?

**Comment by sirago** [comment]
Was there a resolution for this? I'm getting the same error... I'm sure my connection info is correct but I'm getting not authorized for update on (db)

**Comment by stewhouston** [comment]
Bump. This issue has been closed but I cannot authenticate with/to MongoLabs. Mongo 3 uses SCRAM-SHA-1 as its auth protocol.

**Comment by onderweg** [comment]
Same here. Does not work with Mongolab.

**Comment by stewhouston** [comment]
@onderweg After upgrading to PHP 7, my only option was to use [this](https://github.com/mongodb/mongo-php-library) library built on the MongoDB pecl extension. It has a few quirks contrasted with PHP's deprecated Mongo library, but has done the trick for me.

**Comment by onderweg** [comment]
Thanks @stewhouston, but that library depends on the mongodb extension being installed. And since my project is on shared hosting (Dreamhost), that is a problem. So I'm really looking forward to a pure PHP solution.
