### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by steelbrain** [mongofill/mongofill#84]
It's missing a break statement here https://github.com/mongofill/mongofill/blob/master/src/Mongofill/Bson.php#L213
Is it the expected behavior or a bug?

**Comment by steelbrain** [comment]
Also this is an unused variable https://github.com/mongofill/mongofill/blob/master/src/Mongofill/Protocol.php#L27

**Comment by steelbrain** [comment]
and here's an unnecessary assignment https://github.com/mongofill/mongofill/blob/master/src/Mongofill/Protocol.php#L149

**Comment by mcuadros** [comment]
fill to make a PR with this improvements.
