### ISSUE TITLE
Insert document with empty array

### ISSUE THREAD

**Issue by guilhermegeek** [mongofill/mongofill#87]
Hello, this issue was created [here](https://github.com/mongofill/mongofill-hhvm/issues/40#issuecomment-123369759) and i was told to ask here.

With HHVM i'm trying to insert a document having an empty array. It's inserted as an empty object.

```
$m = new MongoClient('mongodb://localhost/testdbb');
$db = $m->db;
$obj = array('name' => 'asd', 'emptyArray' => array());
$res = $db->test->insert($obj);
```

The result:

```
{
    "name" : "asd",
    "emptyArray" : {},
    "_id" : ObjectId("559c3be4049f20b32a9dface")
}
```

Should'nt **emptyArray** be an array instead of an Object?

As [bogomips](https://github.com/bogomips) said, the only way we can create an empty array is using 

```
array(array())
```

**Comment by gui-com-pt** [comment]
Closing the issue, it's not relevant anymore.
